pantalla: 
 ancho: 1000
 alto: 700


tipos:
 - nombre: barraca
   imagen: img/elfos/CASA.png
   ancho_base: 2
   alto_base: 2
   pixel_ref_x: -50
   pixel_ref_y: 150

 - nombre: arqueriaElfos
   imagen: img/1elfos/ARQUERIA.png
   ancho_base: 4
   alto_base: 4
   pixel_ref_x: -90
   pixel_ref_y: 360
   raza: Elfos

 - nombre: caballeriaElfos
   imagen: img/1elfos/CABALLERIA.png
   ancho_base: 3
   alto_base: 3
   pixel_ref_x: -70
   pixel_ref_y: 320
   raza: Elfo

 - nombre: centro civico Elfos
   imagen: img/1elfos/CENTRO-CIVICO.png
   ancho_base: 4
   alto_base: 4
   pixel_ref_x: -90
   pixel_ref_y: 270
   raza: Elfo

 - nombre: molElfos
   imagen: img/1elfos/MOLINO.png
   ancho_base: 2
   alto_base: 2
   pixel_ref_x: -50
   pixel_ref_y: 80
   raza: Elfo

 - nombre: soldado
   imagen: img/1elfos/legolas/WALK.png
   imagen_quieto: img/1elfos/legolas/STAND.png
   imagen_atacar: img/1elfos/legolas/ATACK.png
   fps: 4
   delay: 0
   velocidad: 8
   vida: 50
   armadura: 10
   construccion: 10
   recoleccion: 10   
   fuerza: 10

 - nombre: wheel
   imagen: img/dibujo_dinamico/wheel.png
   pixel_ref_x: -47
   pixel_ref_y: 50
   fps: 20
   delay: 50

 - nombre: herreria
   imagen: img/dibujo_dinamico/mirador.png
   pixel_ref_x: 60
   pixel_ref_y: 50   
   fps: 20
   delay: 50

 - nombre: pino
   imagen: img/dibujo_estatico/arbol/pinetree.png
   pixel_ref_x: 85
   pixel_ref_y: 88

 - nombre: church
   imagen: img/dibujo_estatico/construcciones/church.png
   pixel_ref_x: 60
   pixel_ref_y: 52

 - nombre: oro
   imagen: img/oro.png
   pixel_ref_x: 10
   pixel_ref_y: 0 

 - nombre: piedra
   imagen: img/piedra.png
   pixel_ref_x: 10
   pixel_ref_y: 3

 - nombre: madera
   imagen: img/dibujo_estatico/arbol/pinetree.png
   pixel_ref_x: 16
   pixel_ref_y: 120

 - nombre: firestation
   imagen: img/dibujo_estatico/construcciones/firestation.png
   pixel_ref_x: 0
   pixel_ref_y: 44

 - nombre: arbol
   imagen: img/dibujo_estatico/arbol/firtree.png
   pixel_ref_x: 60
   pixel_ref_y: 20

protagonista:
   - tipo: soldado
     x: 10
     y: 10

jugador:
 nombre: andy
 ip: 127.0.0.1
 raza: Elfo

